// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UpdateUserRequest
	CreateUserRequest
	User
	UserCollection
	UserData
	UserAttributes
	ExistingUserRelationships
	NewUserRelationships
	UpdateRoleRequest
	CreateRoleRequest
	Role
	RoleCollection
	RoleData
	RoleAttributes
	ExistingRoleRelationships
	NewRoleRelationships
	UpdatePermissionRequest
	CreatePermissionRequest
	Permission
	PermissionCollection
	PermissionData
	PermissionAttributes
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "google.golang.org/genproto/protobuf/field_mask"
import google_protobuf2 "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf3 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf4 "github.com/golang/protobuf/ptypes/any"
import dictybase_api_jsonapi "github.com/dictyBase/go-genproto/dictybaseapis/api/jsonapi"
import dictybase_api_jsonapi1 "github.com/dictyBase/go-genproto/dictybaseapis/api/jsonapi"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateUserRequest struct {
	Data *UpdateUserRequest_Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	// An optional mask specifying which fields to update.
	// Presence of this field allow partial updates.
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateUserRequest) GetData() *UpdateUserRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateUserRequest_Data struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Unique id, required
	Id            int64                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Attributes    *UserAttributes       `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Relationships *NewUserRelationships `protobuf:"bytes,4,opt,name=relationships" json:"relationships,omitempty"`
}

func (m *UpdateUserRequest_Data) Reset()                    { *m = UpdateUserRequest_Data{} }
func (m *UpdateUserRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest_Data) ProtoMessage()               {}
func (*UpdateUserRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *UpdateUserRequest_Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateUserRequest_Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUserRequest_Data) GetAttributes() *UserAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *UpdateUserRequest_Data) GetRelationships() *NewUserRelationships {
	if m != nil {
		return m.Relationships
	}
	return nil
}

type CreateUserRequest struct {
	Data *CreateUserRequest_Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserRequest) GetData() *CreateUserRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// The payload for new user
type CreateUserRequest_Data struct {
	Type          string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Attributes    *UserAttributes       `protobuf:"bytes,2,opt,name=attributes" json:"attributes,omitempty"`
	Relationships *NewUserRelationships `protobuf:"bytes,3,opt,name=relationships" json:"relationships,omitempty"`
}

func (m *CreateUserRequest_Data) Reset()                    { *m = CreateUserRequest_Data{} }
func (m *CreateUserRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest_Data) ProtoMessage()               {}
func (*CreateUserRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *CreateUserRequest_Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateUserRequest_Data) GetAttributes() *UserAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *CreateUserRequest_Data) GetRelationships() *NewUserRelationships {
	if m != nil {
		return m.Relationships
	}
	return nil
}

// A user resource.
type User struct {
	Data     *UserData               `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Included []*google_protobuf4.Any `protobuf:"bytes,3,rep,name=included" json:"included,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *User) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *User) GetIncluded() []*google_protobuf4.Any {
	if m != nil {
		return m.Included
	}
	return nil
}

// A user collection resource.
type UserCollection struct {
	Data     []*UserData                            `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Links    *dictybase_api_jsonapi.PaginationLinks `protobuf:"bytes,2,opt,name=links" json:"links,omitempty"`
	Meta     *dictybase_api_jsonapi.Meta            `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
	Included []*google_protobuf4.Any                `protobuf:"bytes,4,rep,name=included" json:"included,omitempty"`
}

func (m *UserCollection) Reset()                    { *m = UserCollection{} }
func (m *UserCollection) String() string            { return proto.CompactTextString(m) }
func (*UserCollection) ProtoMessage()               {}
func (*UserCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserCollection) GetData() []*UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserCollection) GetLinks() *dictybase_api_jsonapi.PaginationLinks {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *UserCollection) GetMeta() *dictybase_api_jsonapi.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *UserCollection) GetIncluded() []*google_protobuf4.Any {
	if m != nil {
		return m.Included
	}
	return nil
}

// A top level container for user data.
type UserData struct {
	// The resource name.
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Unique id.
	Id            int64                        `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Attributes    *UserAttributes              `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Links         *dictybase_api_jsonapi.Links `protobuf:"bytes,4,opt,name=links" json:"links,omitempty"`
	Relationships *ExistingUserRelationships   `protobuf:"bytes,5,opt,name=relationships" json:"relationships,omitempty"`
}

func (m *UserData) Reset()                    { *m = UserData{} }
func (m *UserData) String() string            { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()               {}
func (*UserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserData) GetAttributes() *UserAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *UserData) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *UserData) GetRelationships() *ExistingUserRelationships {
	if m != nil {
		return m.Relationships
	}
	return nil
}

// A container for user fields.
type UserAttributes struct {
	// First name.
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// Last name.
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// Email.
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	// Organization in which the user belong.
	Organization string `protobuf:"bytes,4,opt,name=organization" json:"organization,omitempty"`
	// Group in which the user belong.
	GroupName string `protobuf:"bytes,5,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
	// Address.
	FirstAddress string `protobuf:"bytes,6,opt,name=first_address,json=firstAddress" json:"first_address,omitempty"`
	// More address.
	SecondAddress string `protobuf:"bytes,7,opt,name=second_address,json=secondAddress" json:"second_address,omitempty"`
	// City.
	City string `protobuf:"bytes,8,opt,name=city" json:"city,omitempty"`
	// State.
	State string `protobuf:"bytes,9,opt,name=state" json:"state,omitempty"`
	// Zipcode.
	Zipcode string `protobuf:"bytes,10,opt,name=zipcode" json:"zipcode,omitempty"`
	// Country.
	Country string `protobuf:"bytes,11,opt,name=country" json:"country,omitempty"`
	// Phone no.
	Phone string `protobuf:"bytes,12,opt,name=phone" json:"phone,omitempty"`
	// Current status of user.
	IsActive bool `protobuf:"varint,13,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	// Timestamp for creation and update
	CreatedAt *google_protobuf2.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf2.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *UserAttributes) Reset()                    { *m = UserAttributes{} }
func (m *UserAttributes) String() string            { return proto.CompactTextString(m) }
func (*UserAttributes) ProtoMessage()               {}
func (*UserAttributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserAttributes) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserAttributes) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserAttributes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserAttributes) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *UserAttributes) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *UserAttributes) GetFirstAddress() string {
	if m != nil {
		return m.FirstAddress
	}
	return ""
}

func (m *UserAttributes) GetSecondAddress() string {
	if m != nil {
		return m.SecondAddress
	}
	return ""
}

func (m *UserAttributes) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserAttributes) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *UserAttributes) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

func (m *UserAttributes) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *UserAttributes) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserAttributes) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *UserAttributes) GetCreatedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserAttributes) GetUpdatedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// The relationship definition for existing users.
type ExistingUserRelationships struct {
	Roles *ExistingUserRelationships_Roles `protobuf:"bytes,1,opt,name=roles" json:"roles,omitempty"`
}

func (m *ExistingUserRelationships) Reset()                    { *m = ExistingUserRelationships{} }
func (m *ExistingUserRelationships) String() string            { return proto.CompactTextString(m) }
func (*ExistingUserRelationships) ProtoMessage()               {}
func (*ExistingUserRelationships) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExistingUserRelationships) GetRoles() *ExistingUserRelationships_Roles {
	if m != nil {
		return m.Roles
	}
	return nil
}

// Relationships with role resource.
type ExistingUserRelationships_Roles struct {
	// Http links with role resource.
	Links *dictybase_api_jsonapi.Links `protobuf:"bytes,1,opt,name=links" json:"links,omitempty"`
	// A role [resource identifier object](http://jsonapi.org/format/#document-resource-identifier-objects).
	Data []*dictybase_api_jsonapi.Data `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *ExistingUserRelationships_Roles) Reset()         { *m = ExistingUserRelationships_Roles{} }
func (m *ExistingUserRelationships_Roles) String() string { return proto.CompactTextString(m) }
func (*ExistingUserRelationships_Roles) ProtoMessage()    {}
func (*ExistingUserRelationships_Roles) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

func (m *ExistingUserRelationships_Roles) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *ExistingUserRelationships_Roles) GetData() []*dictybase_api_jsonapi.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// The relationship definition for creating new users.
type NewUserRelationships struct {
	Roles *NewUserRelationships_Roles `protobuf:"bytes,1,opt,name=roles" json:"roles,omitempty"`
}

func (m *NewUserRelationships) Reset()                    { *m = NewUserRelationships{} }
func (m *NewUserRelationships) String() string            { return proto.CompactTextString(m) }
func (*NewUserRelationships) ProtoMessage()               {}
func (*NewUserRelationships) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NewUserRelationships) GetRoles() *NewUserRelationships_Roles {
	if m != nil {
		return m.Roles
	}
	return nil
}

// Relationships with role resource.
type NewUserRelationships_Roles struct {
	// A role [resource identifier object](http://jsonapi.org/format/#document-resource-identifier-objects).
	Data []*dictybase_api_jsonapi.Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *NewUserRelationships_Roles) Reset()                    { *m = NewUserRelationships_Roles{} }
func (m *NewUserRelationships_Roles) String() string            { return proto.CompactTextString(m) }
func (*NewUserRelationships_Roles) ProtoMessage()               {}
func (*NewUserRelationships_Roles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *NewUserRelationships_Roles) GetData() []*dictybase_api_jsonapi.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRoleRequest struct {
	Data *UpdateRoleRequest_Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	// An optional mask specifying which fields to update.
	// Presence of this field allow partial updates.
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdateRoleRequest) Reset()                    { *m = UpdateRoleRequest{} }
func (m *UpdateRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRoleRequest) ProtoMessage()               {}
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRoleRequest) GetData() *UpdateRoleRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateRoleRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateRoleRequest_Data struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Unique id, required
	Id            int64                      `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Attributes    *RoleAttributes            `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Relationships *ExistingRoleRelationships `protobuf:"bytes,4,opt,name=relationships" json:"relationships,omitempty"`
}

func (m *UpdateRoleRequest_Data) Reset()                    { *m = UpdateRoleRequest_Data{} }
func (m *UpdateRoleRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*UpdateRoleRequest_Data) ProtoMessage()               {}
func (*UpdateRoleRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *UpdateRoleRequest_Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateRoleRequest_Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRoleRequest_Data) GetAttributes() *RoleAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *UpdateRoleRequest_Data) GetRelationships() *ExistingRoleRelationships {
	if m != nil {
		return m.Relationships
	}
	return nil
}

type CreateRoleRequest struct {
	Data *CreateRoleRequest_Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *CreateRoleRequest) Reset()                    { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()               {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateRoleRequest) GetData() *CreateRoleRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// The payload for new role
type CreateRoleRequest_Data struct {
	Type          string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Attributes    *RoleAttributes       `protobuf:"bytes,2,opt,name=attributes" json:"attributes,omitempty"`
	Relationships *NewRoleRelationships `protobuf:"bytes,3,opt,name=relationships" json:"relationships,omitempty"`
}

func (m *CreateRoleRequest_Data) Reset()                    { *m = CreateRoleRequest_Data{} }
func (m *CreateRoleRequest_Data) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleRequest_Data) ProtoMessage()               {}
func (*CreateRoleRequest_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *CreateRoleRequest_Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateRoleRequest_Data) GetAttributes() *RoleAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *CreateRoleRequest_Data) GetRelationships() *NewRoleRelationships {
	if m != nil {
		return m.Relationships
	}
	return nil
}

// A definition for managing user roles.
type Role struct {
	Data     *RoleData               `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Included []*google_protobuf4.Any `protobuf:"bytes,3,rep,name=included" json:"included,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Role) GetData() *RoleData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Role) GetIncluded() []*google_protobuf4.Any {
	if m != nil {
		return m.Included
	}
	return nil
}

// A role collection definition.
type RoleCollection struct {
	Data     []*RoleData                  `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Links    *dictybase_api_jsonapi.Links `protobuf:"bytes,2,opt,name=links" json:"links,omitempty"`
	Included []*google_protobuf4.Any      `protobuf:"bytes,3,rep,name=included" json:"included,omitempty"`
}

func (m *RoleCollection) Reset()                    { *m = RoleCollection{} }
func (m *RoleCollection) String() string            { return proto.CompactTextString(m) }
func (*RoleCollection) ProtoMessage()               {}
func (*RoleCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RoleCollection) GetData() []*RoleData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RoleCollection) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *RoleCollection) GetIncluded() []*google_protobuf4.Any {
	if m != nil {
		return m.Included
	}
	return nil
}

// A top level container for role data.
type RoleData struct {
	Type          string                       `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Id            int64                        `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Attributes    *RoleAttributes              `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Links         *dictybase_api_jsonapi.Links `protobuf:"bytes,4,opt,name=links" json:"links,omitempty"`
	Relationships *ExistingRoleRelationships   `protobuf:"bytes,5,opt,name=relationships" json:"relationships,omitempty"`
}

func (m *RoleData) Reset()                    { *m = RoleData{} }
func (m *RoleData) String() string            { return proto.CompactTextString(m) }
func (*RoleData) ProtoMessage()               {}
func (*RoleData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RoleData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RoleData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleData) GetAttributes() *RoleAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *RoleData) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *RoleData) GetRelationships() *ExistingRoleRelationships {
	if m != nil {
		return m.Relationships
	}
	return nil
}

// A container for role fields.
type RoleAttributes struct {
	Role        string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Timestamp for creation and update
	CreatedAt *google_protobuf2.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf2.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *RoleAttributes) Reset()                    { *m = RoleAttributes{} }
func (m *RoleAttributes) String() string            { return proto.CompactTextString(m) }
func (*RoleAttributes) ProtoMessage()               {}
func (*RoleAttributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RoleAttributes) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RoleAttributes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RoleAttributes) GetCreatedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *RoleAttributes) GetUpdatedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// The relationship definition for existing roles.
type ExistingRoleRelationships struct {
	Permissions *ExistingRoleRelationships_Permissions `protobuf:"bytes,1,opt,name=permissions" json:"permissions,omitempty"`
	Users       *ExistingRoleRelationships_Users       `protobuf:"bytes,2,opt,name=users" json:"users,omitempty"`
}

func (m *ExistingRoleRelationships) Reset()                    { *m = ExistingRoleRelationships{} }
func (m *ExistingRoleRelationships) String() string            { return proto.CompactTextString(m) }
func (*ExistingRoleRelationships) ProtoMessage()               {}
func (*ExistingRoleRelationships) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ExistingRoleRelationships) GetPermissions() *ExistingRoleRelationships_Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *ExistingRoleRelationships) GetUsers() *ExistingRoleRelationships_Users {
	if m != nil {
		return m.Users
	}
	return nil
}

// Relationships with permission definition.
type ExistingRoleRelationships_Permissions struct {
	Links *dictybase_api_jsonapi.Links `protobuf:"bytes,1,opt,name=links" json:"links,omitempty"`
	Data  *dictybase_api_jsonapi.Data  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *ExistingRoleRelationships_Permissions) Reset()         { *m = ExistingRoleRelationships_Permissions{} }
func (m *ExistingRoleRelationships_Permissions) String() string { return proto.CompactTextString(m) }
func (*ExistingRoleRelationships_Permissions) ProtoMessage()    {}
func (*ExistingRoleRelationships_Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14, 0}
}

func (m *ExistingRoleRelationships_Permissions) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *ExistingRoleRelationships_Permissions) GetData() *dictybase_api_jsonapi.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// Relationships with user definition.
type ExistingRoleRelationships_Users struct {
	Links *dictybase_api_jsonapi.Links  `protobuf:"bytes,1,opt,name=links" json:"links,omitempty"`
	Data  []*dictybase_api_jsonapi.Data `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *ExistingRoleRelationships_Users) Reset()         { *m = ExistingRoleRelationships_Users{} }
func (m *ExistingRoleRelationships_Users) String() string { return proto.CompactTextString(m) }
func (*ExistingRoleRelationships_Users) ProtoMessage()    {}
func (*ExistingRoleRelationships_Users) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14, 1}
}

func (m *ExistingRoleRelationships_Users) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *ExistingRoleRelationships_Users) GetData() []*dictybase_api_jsonapi.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// The relationship definition for creating new roles.
type NewRoleRelationships struct {
	Permissions *NewRoleRelationships_Permissions `protobuf:"bytes,1,opt,name=permissions" json:"permissions,omitempty"`
	Users       *NewRoleRelationships_Users       `protobuf:"bytes,2,opt,name=users" json:"users,omitempty"`
}

func (m *NewRoleRelationships) Reset()                    { *m = NewRoleRelationships{} }
func (m *NewRoleRelationships) String() string            { return proto.CompactTextString(m) }
func (*NewRoleRelationships) ProtoMessage()               {}
func (*NewRoleRelationships) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *NewRoleRelationships) GetPermissions() *NewRoleRelationships_Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *NewRoleRelationships) GetUsers() *NewRoleRelationships_Users {
	if m != nil {
		return m.Users
	}
	return nil
}

type NewRoleRelationships_Permissions struct {
	Data *dictybase_api_jsonapi.Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *NewRoleRelationships_Permissions) Reset()         { *m = NewRoleRelationships_Permissions{} }
func (m *NewRoleRelationships_Permissions) String() string { return proto.CompactTextString(m) }
func (*NewRoleRelationships_Permissions) ProtoMessage()    {}
func (*NewRoleRelationships_Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 0}
}

func (m *NewRoleRelationships_Permissions) GetData() *dictybase_api_jsonapi.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type NewRoleRelationships_Users struct {
	Data *dictybase_api_jsonapi.Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *NewRoleRelationships_Users) Reset()                    { *m = NewRoleRelationships_Users{} }
func (m *NewRoleRelationships_Users) String() string            { return proto.CompactTextString(m) }
func (*NewRoleRelationships_Users) ProtoMessage()               {}
func (*NewRoleRelationships_Users) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 1} }

func (m *NewRoleRelationships_Users) GetData() *dictybase_api_jsonapi.Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdatePermissionRequest struct {
	Data *UpdatePermissionRequest_Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	// An optional mask specifying which fields to update.
	// Presence of this field allow partial updates.
	UpdateMask *google_protobuf1.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask" json:"update_mask,omitempty"`
}

func (m *UpdatePermissionRequest) Reset()                    { *m = UpdatePermissionRequest{} }
func (m *UpdatePermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePermissionRequest) ProtoMessage()               {}
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *UpdatePermissionRequest) GetData() *UpdatePermissionRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdatePermissionRequest) GetUpdateMask() *google_protobuf1.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdatePermissionRequest_Data struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Unique id, required
	Id         int64                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Attributes *PermissionAttributes `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
}

func (m *UpdatePermissionRequest_Data) Reset()         { *m = UpdatePermissionRequest_Data{} }
func (m *UpdatePermissionRequest_Data) String() string { return proto.CompactTextString(m) }
func (*UpdatePermissionRequest_Data) ProtoMessage()    {}
func (*UpdatePermissionRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16, 0}
}

func (m *UpdatePermissionRequest_Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdatePermissionRequest_Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePermissionRequest_Data) GetAttributes() *PermissionAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type CreatePermissionRequest struct {
	Data *CreatePermissionRequest_Data `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *CreatePermissionRequest) Reset()                    { *m = CreatePermissionRequest{} }
func (m *CreatePermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePermissionRequest) ProtoMessage()               {}
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreatePermissionRequest) GetData() *CreatePermissionRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

// The payload for new user
type CreatePermissionRequest_Data struct {
	Type       string                `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Attributes *PermissionAttributes `protobuf:"bytes,2,opt,name=attributes" json:"attributes,omitempty"`
}

func (m *CreatePermissionRequest_Data) Reset()         { *m = CreatePermissionRequest_Data{} }
func (m *CreatePermissionRequest_Data) String() string { return proto.CompactTextString(m) }
func (*CreatePermissionRequest_Data) ProtoMessage()    {}
func (*CreatePermissionRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17, 0}
}

func (m *CreatePermissionRequest_Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreatePermissionRequest_Data) GetAttributes() *PermissionAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// A resource for managing user permission.
type Permission struct {
	Data *PermissionData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *Permission) Reset()                    { *m = Permission{} }
func (m *Permission) String() string            { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()               {}
func (*Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Permission) GetData() *PermissionData {
	if m != nil {
		return m.Data
	}
	return nil
}

// A permission collection resource.
type PermissionCollection struct {
	Data  []*PermissionData            `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Links *dictybase_api_jsonapi.Links `protobuf:"bytes,2,opt,name=links" json:"links,omitempty"`
}

func (m *PermissionCollection) Reset()                    { *m = PermissionCollection{} }
func (m *PermissionCollection) String() string            { return proto.CompactTextString(m) }
func (*PermissionCollection) ProtoMessage()               {}
func (*PermissionCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PermissionCollection) GetData() []*PermissionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PermissionCollection) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

// A top level container for permission data.
type PermissionData struct {
	// The resource name.
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Unique id.
	Id         int64                        `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Attributes *PermissionAttributes        `protobuf:"bytes,3,opt,name=attributes" json:"attributes,omitempty"`
	Links      *dictybase_api_jsonapi.Links `protobuf:"bytes,4,opt,name=links" json:"links,omitempty"`
}

func (m *PermissionData) Reset()                    { *m = PermissionData{} }
func (m *PermissionData) String() string            { return proto.CompactTextString(m) }
func (*PermissionData) ProtoMessage()               {}
func (*PermissionData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PermissionData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PermissionData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PermissionData) GetAttributes() *PermissionAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *PermissionData) GetLinks() *dictybase_api_jsonapi.Links {
	if m != nil {
		return m.Links
	}
	return nil
}

// A container for permission fields.
type PermissionAttributes struct {
	// Kind of permission.
	Permission string `protobuf:"bytes,1,opt,name=permission" json:"permission,omitempty"`
	// Brief description of the type of permission.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Timestamp for creation and update
	CreatedAt *google_protobuf2.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf2.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *PermissionAttributes) Reset()                    { *m = PermissionAttributes{} }
func (m *PermissionAttributes) String() string            { return proto.CompactTextString(m) }
func (*PermissionAttributes) ProtoMessage()               {}
func (*PermissionAttributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PermissionAttributes) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *PermissionAttributes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PermissionAttributes) GetCreatedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PermissionAttributes) GetUpdatedAt() *google_protobuf2.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateUserRequest)(nil), "dictybase.user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserRequest_Data)(nil), "dictybase.user.UpdateUserRequest.Data")
	proto.RegisterType((*CreateUserRequest)(nil), "dictybase.user.CreateUserRequest")
	proto.RegisterType((*CreateUserRequest_Data)(nil), "dictybase.user.CreateUserRequest.Data")
	proto.RegisterType((*User)(nil), "dictybase.user.User")
	proto.RegisterType((*UserCollection)(nil), "dictybase.user.UserCollection")
	proto.RegisterType((*UserData)(nil), "dictybase.user.UserData")
	proto.RegisterType((*UserAttributes)(nil), "dictybase.user.UserAttributes")
	proto.RegisterType((*ExistingUserRelationships)(nil), "dictybase.user.ExistingUserRelationships")
	proto.RegisterType((*ExistingUserRelationships_Roles)(nil), "dictybase.user.ExistingUserRelationships.Roles")
	proto.RegisterType((*NewUserRelationships)(nil), "dictybase.user.NewUserRelationships")
	proto.RegisterType((*NewUserRelationships_Roles)(nil), "dictybase.user.NewUserRelationships.Roles")
	proto.RegisterType((*UpdateRoleRequest)(nil), "dictybase.user.UpdateRoleRequest")
	proto.RegisterType((*UpdateRoleRequest_Data)(nil), "dictybase.user.UpdateRoleRequest.Data")
	proto.RegisterType((*CreateRoleRequest)(nil), "dictybase.user.CreateRoleRequest")
	proto.RegisterType((*CreateRoleRequest_Data)(nil), "dictybase.user.CreateRoleRequest.Data")
	proto.RegisterType((*Role)(nil), "dictybase.user.Role")
	proto.RegisterType((*RoleCollection)(nil), "dictybase.user.RoleCollection")
	proto.RegisterType((*RoleData)(nil), "dictybase.user.RoleData")
	proto.RegisterType((*RoleAttributes)(nil), "dictybase.user.RoleAttributes")
	proto.RegisterType((*ExistingRoleRelationships)(nil), "dictybase.user.ExistingRoleRelationships")
	proto.RegisterType((*ExistingRoleRelationships_Permissions)(nil), "dictybase.user.ExistingRoleRelationships.Permissions")
	proto.RegisterType((*ExistingRoleRelationships_Users)(nil), "dictybase.user.ExistingRoleRelationships.Users")
	proto.RegisterType((*NewRoleRelationships)(nil), "dictybase.user.NewRoleRelationships")
	proto.RegisterType((*NewRoleRelationships_Permissions)(nil), "dictybase.user.NewRoleRelationships.Permissions")
	proto.RegisterType((*NewRoleRelationships_Users)(nil), "dictybase.user.NewRoleRelationships.Users")
	proto.RegisterType((*UpdatePermissionRequest)(nil), "dictybase.user.UpdatePermissionRequest")
	proto.RegisterType((*UpdatePermissionRequest_Data)(nil), "dictybase.user.UpdatePermissionRequest.Data")
	proto.RegisterType((*CreatePermissionRequest)(nil), "dictybase.user.CreatePermissionRequest")
	proto.RegisterType((*CreatePermissionRequest_Data)(nil), "dictybase.user.CreatePermissionRequest.Data")
	proto.RegisterType((*Permission)(nil), "dictybase.user.Permission")
	proto.RegisterType((*PermissionCollection)(nil), "dictybase.user.PermissionCollection")
	proto.RegisterType((*PermissionData)(nil), "dictybase.user.PermissionData")
	proto.RegisterType((*PermissionAttributes)(nil), "dictybase.user.PermissionAttributes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	// Gets the specified user
	GetUser(ctx context.Context, in *dictybase_api_jsonapi1.GetRequest, opts ...grpc.CallOption) (*User, error)
	// Gets all related roles
	GetRelatedRoles(ctx context.Context, in *dictybase_api_jsonapi1.RelationshipRequest, opts ...grpc.CallOption) (*RoleCollection, error)
	// List all users
	ListUsers(ctx context.Context, in *dictybase_api_jsonapi1.ListRequest, opts ...grpc.CallOption) (*UserCollection, error)
	// Create an user
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Create relationship links with roles
	CreateRoleRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	// Update an user
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Update relationship links with roles
	UpdateRoleRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	// Delete an user
	DeleteUser(ctx context.Context, in *dictybase_api_jsonapi1.DeleteRequest, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	// Delete relationship links with roles
	DeleteRoleRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *dictybase_api_jsonapi1.GetRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRelatedRoles(ctx context.Context, in *dictybase_api_jsonapi1.RelationshipRequest, opts ...grpc.CallOption) (*RoleCollection, error) {
	out := new(RoleCollection)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/GetRelatedRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *dictybase_api_jsonapi1.ListRequest, opts ...grpc.CallOption) (*UserCollection, error) {
	out := new(UserCollection)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateRoleRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/CreateRoleRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateRoleRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/UpdateRoleRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *dictybase_api_jsonapi1.DeleteRequest, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteRoleRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.UserService/DeleteRoleRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	// Gets the specified user
	GetUser(context.Context, *dictybase_api_jsonapi1.GetRequest) (*User, error)
	// Gets all related roles
	GetRelatedRoles(context.Context, *dictybase_api_jsonapi1.RelationshipRequest) (*RoleCollection, error)
	// List all users
	ListUsers(context.Context, *dictybase_api_jsonapi1.ListRequest) (*UserCollection, error)
	// Create an user
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	// Create relationship links with roles
	CreateRoleRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	// Update an user
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	// Update relationship links with roles
	UpdateRoleRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	// Delete an user
	DeleteUser(context.Context, *dictybase_api_jsonapi1.DeleteRequest) (*google_protobuf3.Empty, error)
	// Delete relationship links with roles
	DeleteRoleRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*dictybase_api_jsonapi1.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRelatedRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.RelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRelatedRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/GetRelatedRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRelatedRoles(ctx, req.(*dictybase_api_jsonapi1.RelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*dictybase_api_jsonapi1.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateRoleRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateRoleRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/CreateRoleRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateRoleRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateRoleRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateRoleRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/UpdateRoleRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateRoleRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*dictybase_api_jsonapi1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteRoleRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteRoleRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.UserService/DeleteRoleRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteRoleRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dictybase.user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetRelatedRoles",
			Handler:    _UserService_GetRelatedRoles_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "CreateRoleRelationship",
			Handler:    _UserService_CreateRoleRelationship_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateRoleRelationship",
			Handler:    _UserService_UpdateRoleRelationship_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "DeleteRoleRelationship",
			Handler:    _UserService_DeleteRoleRelationship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

// Client API for RoleService service

type RoleServiceClient interface {
	// Gets the specified role
	GetRole(ctx context.Context, in *dictybase_api_jsonapi1.GetRequest, opts ...grpc.CallOption) (*Role, error)
	// Gets all related users
	GetRelatedUsers(ctx context.Context, in *dictybase_api_jsonapi1.RelationshipRequest, opts ...grpc.CallOption) (*UserCollection, error)
	// Gets all related permissions
	GetRelatedPermissions(ctx context.Context, in *dictybase_api_jsonapi1.RelationshipRequest, opts ...grpc.CallOption) (*PermissionCollection, error)
	// List all roles
	ListRoles(ctx context.Context, in *dictybase_api_jsonapi1.ListRequest, opts ...grpc.CallOption) (*RoleCollection, error)
	// Create an role
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*Role, error)
	CreateUserRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	CreatePermissionRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	// Update an role
	UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*Role, error)
	UpdateUserRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	UpdatePermissionRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	// Delete an role
	DeleteRole(ctx context.Context, in *dictybase_api_jsonapi1.DeleteRequest, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	DeleteUserRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
	DeletePermissionRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
}

type roleServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoleServiceClient(cc *grpc.ClientConn) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) GetRole(ctx context.Context, in *dictybase_api_jsonapi1.GetRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/GetRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRelatedUsers(ctx context.Context, in *dictybase_api_jsonapi1.RelationshipRequest, opts ...grpc.CallOption) (*UserCollection, error) {
	out := new(UserCollection)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/GetRelatedUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetRelatedPermissions(ctx context.Context, in *dictybase_api_jsonapi1.RelationshipRequest, opts ...grpc.CallOption) (*PermissionCollection, error) {
	out := new(PermissionCollection)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/GetRelatedPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) ListRoles(ctx context.Context, in *dictybase_api_jsonapi1.ListRequest, opts ...grpc.CallOption) (*RoleCollection, error) {
	out := new(RoleCollection)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/ListRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/CreateRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) CreateUserRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/CreateUserRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) CreatePermissionRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/CreatePermissionRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/UpdateRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpdateUserRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/UpdateUserRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpdatePermissionRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/UpdatePermissionRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) DeleteRole(ctx context.Context, in *dictybase_api_jsonapi1.DeleteRequest, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/DeleteRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) DeleteUserRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/DeleteUserRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) DeletePermissionRelationship(ctx context.Context, in *dictybase_api_jsonapi.DataCollection, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.RoleService/DeletePermissionRelationship", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RoleService service

type RoleServiceServer interface {
	// Gets the specified role
	GetRole(context.Context, *dictybase_api_jsonapi1.GetRequest) (*Role, error)
	// Gets all related users
	GetRelatedUsers(context.Context, *dictybase_api_jsonapi1.RelationshipRequest) (*UserCollection, error)
	// Gets all related permissions
	GetRelatedPermissions(context.Context, *dictybase_api_jsonapi1.RelationshipRequest) (*PermissionCollection, error)
	// List all roles
	ListRoles(context.Context, *dictybase_api_jsonapi1.ListRequest) (*RoleCollection, error)
	// Create an role
	CreateRole(context.Context, *CreateRoleRequest) (*Role, error)
	CreateUserRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	CreatePermissionRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	// Update an role
	UpdateRole(context.Context, *UpdateRoleRequest) (*Role, error)
	UpdateUserRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	UpdatePermissionRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	// Delete an role
	DeleteRole(context.Context, *dictybase_api_jsonapi1.DeleteRequest) (*google_protobuf3.Empty, error)
	DeleteUserRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
	DeletePermissionRelationship(context.Context, *dictybase_api_jsonapi.DataCollection) (*google_protobuf3.Empty, error)
}

func RegisterRoleServiceServer(s *grpc.Server, srv RoleServiceServer) {
	s.RegisterService(&_RoleService_serviceDesc, srv)
}

func _RoleService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRole(ctx, req.(*dictybase_api_jsonapi1.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRelatedUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.RelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRelatedUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/GetRelatedUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRelatedUsers(ctx, req.(*dictybase_api_jsonapi1.RelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetRelatedPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.RelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetRelatedPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/GetRelatedPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetRelatedPermissions(ctx, req.(*dictybase_api_jsonapi1.RelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).ListRoles(ctx, req.(*dictybase_api_jsonapi1.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_CreateUserRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).CreateUserRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/CreateUserRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).CreateUserRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_CreatePermissionRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).CreatePermissionRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/CreatePermissionRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).CreatePermissionRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpdateRole(ctx, req.(*UpdateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpdateUserRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpdateUserRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/UpdateUserRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpdateUserRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpdatePermissionRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpdatePermissionRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/UpdatePermissionRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpdatePermissionRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).DeleteRole(ctx, req.(*dictybase_api_jsonapi1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_DeleteUserRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).DeleteUserRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/DeleteUserRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).DeleteUserRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_DeletePermissionRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi.DataCollection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).DeletePermissionRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.RoleService/DeletePermissionRelationship",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).DeletePermissionRelationship(ctx, req.(*dictybase_api_jsonapi.DataCollection))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dictybase.user.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRole",
			Handler:    _RoleService_GetRole_Handler,
		},
		{
			MethodName: "GetRelatedUsers",
			Handler:    _RoleService_GetRelatedUsers_Handler,
		},
		{
			MethodName: "GetRelatedPermissions",
			Handler:    _RoleService_GetRelatedPermissions_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _RoleService_ListRoles_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _RoleService_CreateRole_Handler,
		},
		{
			MethodName: "CreateUserRelationship",
			Handler:    _RoleService_CreateUserRelationship_Handler,
		},
		{
			MethodName: "CreatePermissionRelationship",
			Handler:    _RoleService_CreatePermissionRelationship_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _RoleService_UpdateRole_Handler,
		},
		{
			MethodName: "UpdateUserRelationship",
			Handler:    _RoleService_UpdateUserRelationship_Handler,
		},
		{
			MethodName: "UpdatePermissionRelationship",
			Handler:    _RoleService_UpdatePermissionRelationship_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _RoleService_DeleteRole_Handler,
		},
		{
			MethodName: "DeleteUserRelationship",
			Handler:    _RoleService_DeleteUserRelationship_Handler,
		},
		{
			MethodName: "DeletePermissionRelationship",
			Handler:    _RoleService_DeletePermissionRelationship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

// Client API for PermissionService service

type PermissionServiceClient interface {
	// Gets the specified permission
	GetPermission(ctx context.Context, in *dictybase_api_jsonapi1.GetRequest, opts ...grpc.CallOption) (*Permission, error)
	// List all permissions
	ListPermissions(ctx context.Context, in *dictybase_api_jsonapi1.ListRequest, opts ...grpc.CallOption) (*PermissionCollection, error)
	// Create an permission
	CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*Permission, error)
	// Update an permission
	UpdatePermission(ctx context.Context, in *UpdatePermissionRequest, opts ...grpc.CallOption) (*Permission, error)
	// Delete an permission
	DeletePermission(ctx context.Context, in *dictybase_api_jsonapi1.DeleteRequest, opts ...grpc.CallOption) (*google_protobuf3.Empty, error)
}

type permissionServiceClient struct {
	cc *grpc.ClientConn
}

func NewPermissionServiceClient(cc *grpc.ClientConn) PermissionServiceClient {
	return &permissionServiceClient{cc}
}

func (c *permissionServiceClient) GetPermission(ctx context.Context, in *dictybase_api_jsonapi1.GetRequest, opts ...grpc.CallOption) (*Permission, error) {
	out := new(Permission)
	err := grpc.Invoke(ctx, "/dictybase.user.PermissionService/GetPermission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) ListPermissions(ctx context.Context, in *dictybase_api_jsonapi1.ListRequest, opts ...grpc.CallOption) (*PermissionCollection, error) {
	out := new(PermissionCollection)
	err := grpc.Invoke(ctx, "/dictybase.user.PermissionService/ListPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*Permission, error) {
	out := new(Permission)
	err := grpc.Invoke(ctx, "/dictybase.user.PermissionService/CreatePermission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) UpdatePermission(ctx context.Context, in *UpdatePermissionRequest, opts ...grpc.CallOption) (*Permission, error) {
	out := new(Permission)
	err := grpc.Invoke(ctx, "/dictybase.user.PermissionService/UpdatePermission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) DeletePermission(ctx context.Context, in *dictybase_api_jsonapi1.DeleteRequest, opts ...grpc.CallOption) (*google_protobuf3.Empty, error) {
	out := new(google_protobuf3.Empty)
	err := grpc.Invoke(ctx, "/dictybase.user.PermissionService/DeletePermission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PermissionService service

type PermissionServiceServer interface {
	// Gets the specified permission
	GetPermission(context.Context, *dictybase_api_jsonapi1.GetRequest) (*Permission, error)
	// List all permissions
	ListPermissions(context.Context, *dictybase_api_jsonapi1.ListRequest) (*PermissionCollection, error)
	// Create an permission
	CreatePermission(context.Context, *CreatePermissionRequest) (*Permission, error)
	// Update an permission
	UpdatePermission(context.Context, *UpdatePermissionRequest) (*Permission, error)
	// Delete an permission
	DeletePermission(context.Context, *dictybase_api_jsonapi1.DeleteRequest) (*google_protobuf3.Empty, error)
}

func RegisterPermissionServiceServer(s *grpc.Server, srv PermissionServiceServer) {
	s.RegisterService(&_PermissionService_serviceDesc, srv)
}

func _PermissionService_GetPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).GetPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.PermissionService/GetPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).GetPermission(ctx, req.(*dictybase_api_jsonapi1.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.PermissionService/ListPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).ListPermissions(ctx, req.(*dictybase_api_jsonapi1.ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.PermissionService/CreatePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).CreatePermission(ctx, req.(*CreatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_UpdatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).UpdatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.PermissionService/UpdatePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).UpdatePermission(ctx, req.(*UpdatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_DeletePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dictybase_api_jsonapi1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).DeletePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dictybase.user.PermissionService/DeletePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).DeletePermission(ctx, req.(*dictybase_api_jsonapi1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PermissionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dictybase.user.PermissionService",
	HandlerType: (*PermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPermission",
			Handler:    _PermissionService_GetPermission_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _PermissionService_ListPermissions_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _PermissionService_CreatePermission_Handler,
		},
		{
			MethodName: "UpdatePermission",
			Handler:    _PermissionService_UpdatePermission_Handler,
		},
		{
			MethodName: "DeletePermission",
			Handler:    _PermissionService_DeletePermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1781 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6f, 0xdb, 0x46,
	0x16, 0x07, 0x25, 0x39, 0x96, 0x9e, 0x6c, 0x25, 0x9e, 0x78, 0x63, 0x59, 0xf1, 0x26, 0x5e, 0x26,
	0xd9, 0xf5, 0x0a, 0x59, 0x31, 0xd0, 0x62, 0x81, 0x6c, 0x52, 0x04, 0x76, 0xe2, 0x34, 0x48, 0x91,
	0x0f, 0x83, 0x4d, 0x90, 0xb4, 0x17, 0x97, 0x16, 0xc7, 0xca, 0xd4, 0x12, 0xc9, 0x90, 0xa3, 0x34,
	0x4a, 0xd1, 0x1e, 0xda, 0x5b, 0x80, 0xa2, 0x40, 0x7b, 0xee, 0xa5, 0x28, 0x02, 0xf4, 0xd2, 0x63,
	0x2f, 0x6d, 0x2f, 0x05, 0x7a, 0xe9, 0xa1, 0x28, 0xd0, 0x3f, 0xa0, 0x97, 0x1e, 0x7a, 0xef, 0x25,
	0xc7, 0x62, 0x66, 0x48, 0x71, 0x48, 0x8a, 0x32, 0x65, 0xcb, 0xee, 0xc5, 0x16, 0x67, 0xde, 0xf7,
	0xbc, 0xf7, 0xfb, 0x91, 0x03, 0xd0, 0xf3, 0xb0, 0xdb, 0x70, 0x5c, 0x9b, 0xda, 0xa8, 0x62, 0x92,
	0x16, 0xed, 0x6f, 0x19, 0x1e, 0x6e, 0xb0, 0xd5, 0xda, 0x52, 0xdb, 0xb6, 0xdb, 0x1d, 0xac, 0x19,
	0x0e, 0xd1, 0x0c, 0xcb, 0xb2, 0xa9, 0x41, 0x89, 0x6d, 0x79, 0x42, 0xba, 0xb6, 0xec, 0xef, 0xf2,
	0xa7, 0xad, 0xde, 0xb6, 0xb6, 0x4d, 0x70, 0xc7, 0xdc, 0xec, 0x1a, 0xde, 0x8e, 0x2f, 0x71, 0x3a,
	0x2e, 0x41, 0x49, 0x17, 0x7b, 0xd4, 0xe8, 0x3a, 0xbe, 0xc0, 0xc9, 0xb8, 0x00, 0xee, 0x3a, 0xb4,
	0xef, 0x6f, 0x2e, 0xc6, 0x37, 0x0d, 0x2b, 0xd8, 0x3a, 0x33, 0x08, 0x94, 0xc7, 0xf6, 0xb6, 0x67,
	0x5b, 0xec, 0xbf, 0x63, 0xf4, 0x3b, 0xb6, 0x61, 0x8e, 0x16, 0x72, 0xf1, 0xe3, 0x1e, 0xf6, 0xa8,
	0x10, 0x52, 0x7f, 0xc8, 0xc1, 0xdc, 0x7d, 0xc7, 0x34, 0x28, 0xbe, 0xef, 0x61, 0x57, 0x17, 0x7b,
	0xe8, 0x12, 0x14, 0x4c, 0x83, 0x1a, 0x55, 0x65, 0x59, 0x59, 0x29, 0x37, 0xff, 0xd9, 0x88, 0xd6,
	0xa5, 0x91, 0x50, 0x68, 0xac, 0x1b, 0xd4, 0xd0, 0xb9, 0x0e, 0xba, 0x0c, 0xe5, 0x1e, 0xdf, 0xe7,
	0x95, 0xa8, 0xe6, 0xb8, 0x89, 0x5a, 0x43, 0x24, 0xd3, 0x08, 0x92, 0x69, 0xbc, 0xca, 0x8a, 0x75,
	0xdb, 0xf0, 0x76, 0x74, 0x10, 0xe2, 0xec, 0x77, 0xed, 0x6b, 0x05, 0x0a, 0xcc, 0x16, 0x42, 0x50,
	0xa0, 0x7d, 0x07, 0xf3, 0x08, 0x4a, 0x3a, 0xff, 0x8d, 0x2a, 0x90, 0x23, 0x26, 0x37, 0x98, 0xd7,
	0x73, 0xc4, 0x44, 0x57, 0x00, 0x0c, 0x4a, 0x5d, 0xb2, 0xd5, 0xa3, 0xd8, 0xab, 0xe6, 0xb9, 0xa3,
	0x53, 0x89, 0x58, 0x3d, 0xec, 0xae, 0x0d, 0xa4, 0x74, 0x49, 0x03, 0xbd, 0x06, 0xb3, 0x2e, 0xee,
	0x88, 0x33, 0x7d, 0x44, 0x1c, 0xaf, 0x5a, 0xe0, 0x26, 0xce, 0xc6, 0x4d, 0xdc, 0xc1, 0xef, 0x88,
	0x5c, 0x25, 0x59, 0x3d, 0xaa, 0xaa, 0xbe, 0x54, 0x60, 0xee, 0x9a, 0x8b, 0xc7, 0xab, 0x63, 0x42,
	0x41, 0xaa, 0x63, 0xed, 0xc5, 0xa8, 0x52, 0x44, 0x53, 0xcf, 0xed, 0x3f, 0xf5, 0xfc, 0xde, 0x53,
	0xdf, 0x86, 0x02, 0x93, 0x41, 0xe7, 0x23, 0xc9, 0x56, 0x87, 0x45, 0x23, 0xb5, 0xc9, 0x05, 0x28,
	0x12, 0xab, 0xd5, 0xe9, 0x99, 0xd8, 0xac, 0xe6, 0x97, 0xf3, 0x2b, 0xe5, 0xe6, 0x7c, 0xa2, 0x47,
	0xd6, 0xac, 0xbe, 0x3e, 0x90, 0x52, 0x7f, 0x55, 0xa0, 0xc2, 0x8c, 0x5c, 0xb3, 0x3b, 0x1d, 0xdc,
	0x62, 0xfe, 0x25, 0x97, 0xf9, 0x0c, 0x2e, 0x5f, 0x81, 0xa9, 0x0e, 0xb1, 0x76, 0x82, 0x7a, 0xc9,
	0xc7, 0x61, 0x38, 0xa4, 0xe1, 0x0f, 0x48, 0x63, 0xc3, 0x68, 0x13, 0x8b, 0xe7, 0x77, 0x8b, 0x49,
	0xeb, 0x42, 0x09, 0x69, 0x50, 0xe8, 0x62, 0x6a, 0xf8, 0x95, 0x3a, 0x99, 0xa2, 0x7c, 0x1b, 0x33,
	0x77, 0x4c, 0x30, 0x92, 0x61, 0x21, 0x53, 0x86, 0x7f, 0x28, 0x50, 0x0c, 0x62, 0x3e, 0x94, 0x09,
	0x68, 0x06, 0x15, 0x11, 0x9d, 0xbf, 0x94, 0x92, 0x54, 0xa4, 0x0e, 0x77, 0xe3, 0xad, 0x33, 0xc5,
	0x75, 0xff, 0x1d, 0x77, 0x7b, 0xfd, 0x29, 0xf1, 0x28, 0xb1, 0xda, 0xbb, 0x8f, 0x4e, 0x5e, 0x9c,
	0x6b, 0x18, 0x23, 0xfa, 0x3b, 0xc0, 0x36, 0x71, 0x3d, 0xba, 0x69, 0x19, 0xdd, 0xa0, 0x02, 0x25,
	0xbe, 0x72, 0xc7, 0xe8, 0x62, 0x74, 0x12, 0x4a, 0x1d, 0x23, 0xd8, 0xcd, 0xf1, 0xdd, 0x22, 0x5b,
	0xe0, 0x9b, 0xf3, 0x30, 0x85, 0xbb, 0x06, 0xe9, 0xf0, 0x72, 0x94, 0x74, 0xf1, 0x80, 0x54, 0x98,
	0xb1, 0xdd, 0xb6, 0x61, 0x91, 0x67, 0xdc, 0x33, 0x4f, 0xb8, 0xa4, 0x47, 0xd6, 0x98, 0xd7, 0xb6,
	0x6b, 0xf7, 0x1c, 0x61, 0x77, 0x4a, 0x78, 0xe5, 0x2b, 0xdc, 0xf0, 0x19, 0x98, 0x15, 0x41, 0x19,
	0xa6, 0xe9, 0x62, 0xcf, 0xab, 0x1e, 0x11, 0x36, 0xf8, 0xe2, 0x9a, 0x58, 0x43, 0xe7, 0xa0, 0xe2,
	0xe1, 0x96, 0x6d, 0x99, 0x03, 0xa9, 0x69, 0x2e, 0x35, 0x2b, 0x56, 0x03, 0x31, 0x04, 0x85, 0x16,
	0xa1, 0xfd, 0x6a, 0x51, 0x1c, 0x2e, 0xfb, 0xcd, 0x02, 0xf7, 0xa8, 0x41, 0x71, 0xb5, 0x24, 0x02,
	0xe7, 0x0f, 0xa8, 0x0a, 0xd3, 0xcf, 0x88, 0xd3, 0xb2, 0x4d, 0x5c, 0x05, 0xbe, 0x1e, 0x3c, 0xb2,
	0x9d, 0x96, 0xdd, 0xb3, 0xa8, 0xdb, 0xaf, 0x96, 0xc5, 0x8e, 0xff, 0xc8, 0x2c, 0x39, 0x8f, 0x6c,
	0x0b, 0x57, 0x67, 0x84, 0x25, 0xfe, 0xc0, 0xaa, 0x46, 0xbc, 0x4d, 0xa3, 0x45, 0xc9, 0x13, 0x5c,
	0x9d, 0x5d, 0x56, 0x56, 0x8a, 0x7a, 0x91, 0x78, 0x6b, 0xfc, 0x19, 0xfd, 0x1f, 0xa0, 0xc5, 0xd1,
	0xc8, 0xdc, 0x34, 0x68, 0xb5, 0x92, 0x02, 0xda, 0xf7, 0x02, 0xfe, 0xd2, 0x4b, 0xbe, 0xf4, 0x1a,
	0x65, 0xaa, 0x02, 0xc1, 0xb9, 0xea, 0xd1, 0xdd, 0x55, 0x7d, 0xe9, 0x35, 0xaa, 0xfe, 0xac, 0xc0,
	0x62, 0x6a, 0x9f, 0xa0, 0xeb, 0x30, 0xe5, 0xda, 0x1d, 0xec, 0xf9, 0x88, 0xa2, 0x65, 0xee, 0xb0,
	0x86, 0xce, 0xd4, 0x74, 0xa1, 0x5d, 0xeb, 0xc0, 0x14, 0x7f, 0x0e, 0xbb, 0x5d, 0xc9, 0xde, 0xed,
	0x9a, 0x8f, 0x30, 0x39, 0x3e, 0xc0, 0x69, 0x53, 0x1f, 0x82, 0x8c, 0xfa, 0x89, 0x02, 0xf3, 0xc3,
	0x50, 0x13, 0xad, 0x46, 0xb3, 0xa9, 0x67, 0x81, 0xda, 0x68, 0x22, 0x17, 0x83, 0x44, 0xb4, 0x08,
	0xec, 0x65, 0x08, 0xea, 0xc7, 0x01, 0xcb, 0x33, 0x03, 0x63, 0xb1, 0xbc, 0xa4, 0x30, 0x31, 0x96,
	0xff, 0x66, 0xe2, 0x2c, 0xcf, 0xa2, 0x4c, 0xc1, 0xb8, 0xbb, 0xc3, 0x59, 0x3e, 0x15, 0xaf, 0x44,
	0xc2, 0x99, 0xa8, 0x7e, 0x8c, 0x62, 0x26, 0x14, 0x26, 0x4b, 0xf5, 0x23, 0xf2, 0x1f, 0x83, 0xea,
	0x77, 0x4d, 0x7d, 0x1b, 0x0a, 0x4c, 0x66, 0x37, 0xaa, 0x67, 0x32, 0xfb, 0xa2, 0xfa, 0x2f, 0x14,
	0xa8, 0x30, 0x23, 0xd9, 0xa9, 0x3e, 0xe6, 0xb2, 0x19, 0xa5, 0xfa, 0x4c, 0xa3, 0x3e, 0x7e, 0x98,
	0x8c, 0xaf, 0x03, 0xc7, 0x87, 0xd2, 0xcb, 0x87, 0xc1, 0xd7, 0xbb, 0x36, 0xc1, 0xb7, 0xfe, 0xe1,
	0x48, 0x7c, 0x8d, 0xa0, 0xc0, 0x20, 0x2a, 0xc8, 0x9d, 0xfd, 0x46, 0xcb, 0x50, 0x36, 0xb1, 0xd7,
	0x72, 0x89, 0xc3, 0x09, 0x57, 0xd0, 0xb4, 0xbc, 0xf4, 0x17, 0x71, 0xce, 0x67, 0xf9, 0x90, 0x73,
	0x12, 0xb9, 0xa2, 0x07, 0x50, 0x76, 0xb0, 0xdb, 0x25, 0x9e, 0xc7, 0x96, 0xfc, 0x06, 0xff, 0x5f,
	0xe6, 0x5a, 0x35, 0x36, 0x42, 0x65, 0x5d, 0xb6, 0xc4, 0xc8, 0x8c, 0xa9, 0x06, 0x1d, 0xa9, 0x65,
	0x37, 0xc9, 0x58, 0xc1, 0xd3, 0x85, 0x76, 0xcd, 0x85, 0xb2, 0xe4, 0x62, 0x9f, 0x94, 0xa6, 0x64,
	0x62, 0x0f, 0x46, 0xa0, 0x3c, 0x86, 0xc3, 0x21, 0xd0, 0x17, 0x39, 0x4e, 0xa0, 0xc9, 0xa3, 0xd1,
	0x87, 0x1d, 0xcd, 0x85, 0x2c, 0x30, 0x96, 0x7e, 0x2a, 0xab, 0xd1, 0x53, 0xa9, 0x67, 0xb2, 0x16,
	0x39, 0x90, 0x2b, 0xd1, 0x03, 0xd1, 0x22, 0xc8, 0x98, 0xa1, 0xb8, 0x17, 0x83, 0xe2, 0x8e, 0xab,
	0xa9, 0x3e, 0xcf, 0xc1, 0x82, 0xe0, 0xe8, 0x30, 0x80, 0x80, 0x8d, 0x56, 0x23, 0xc6, 0xce, 0x0f,
	0xa7, 0xf6, 0x84, 0xda, 0xc4, 0x08, 0xde, 0x19, 0x83, 0xdf, 0xd7, 0x87, 0x60, 0x62, 0x82, 0x9c,
	0xc2, 0x50, 0x87, 0x23, 0xa3, 0xfa, 0x9d, 0x02, 0x0b, 0x82, 0x63, 0xc7, 0x2e, 0x46, 0x8a, 0x9a,
	0x7c, 0x48, 0x6f, 0x8d, 0xc8, 0x67, 0x7d, 0x08, 0x3f, 0x8f, 0x1f, 0xff, 0x2a, 0x40, 0x28, 0x83,
	0x9a, 0x91, 0x88, 0x4f, 0xa5, 0x5b, 0x93, 0xda, 0xe1, 0x7d, 0x98, 0x0f, 0xd7, 0x25, 0xe2, 0x6c,
	0x46, 0x88, 0x33, 0x93, 0xad, 0xbd, 0xd0, 0xa7, 0xfa, 0x95, 0x02, 0x95, 0xa8, 0xb1, 0xc3, 0x3b,
	0xfe, 0xbd, 0x10, 0xa3, 0xfa, 0x93, 0x22, 0x57, 0x4c, 0x62, 0xb3, 0x53, 0x00, 0x21, 0x46, 0xf8,
	0xc1, 0x4b, 0x2b, 0x63, 0x33, 0x5b, 0x7e, 0xef, 0xcc, 0x56, 0x18, 0x83, 0xd9, 0x9a, 0xbf, 0x4f,
	0x43, 0x99, 0x61, 0xc9, 0xeb, 0xd8, 0x7d, 0x42, 0x5a, 0x18, 0x3d, 0x80, 0xe9, 0x1b, 0x98, 0xf2,
	0xbb, 0x99, 0x7f, 0xa4, 0x14, 0xe4, 0x06, 0xa6, 0x7e, 0xbb, 0xd7, 0xe6, 0x87, 0xdd, 0x1b, 0xa8,
	0xc7, 0x3f, 0xf8, 0xe5, 0xb7, 0x4f, 0x73, 0xb3, 0xa8, 0xac, 0x71, 0xb8, 0xd3, 0xde, 0x25, 0xe6,
	0x7b, 0xe8, 0x29, 0x1c, 0xe5, 0x8a, 0x1d, 0xe6, 0x58, 0x7c, 0x92, 0xd4, 0x53, 0x1c, 0xc8, 0xc8,
	0x19, 0x78, 0x1a, 0xfa, 0xc6, 0x13, 0x76, 0xac, 0xba, 0xc8, 0x7d, 0x1e, 0x47, 0x73, 0x92, 0x4f,
	0x8d, 0x7f, 0x02, 0xa1, 0x4d, 0x28, 0xdd, 0x22, 0x1e, 0x15, 0x88, 0xa9, 0xa6, 0x9e, 0xb2, 0x47,
	0x53, 0x7d, 0x45, 0x6f, 0x90, 0xd4, 0x0a, 0xf7, 0x55, 0x44, 0x47, 0x84, 0x2f, 0xf4, 0x10, 0x20,
	0xbc, 0x95, 0x8b, 0x94, 0x6d, 0xf8, 0x8d, 0x5d, 0x4a, 0xd9, 0xe6, 0xb8, 0xd9, 0xb2, 0xea, 0x9b,
	0xbd, 0xa4, 0xd4, 0xd1, 0x87, 0x0a, 0x9c, 0x90, 0xbf, 0x02, 0xc2, 0xba, 0xa0, 0x73, 0x23, 0xc0,
	0x3e, 0x8c, 0xb5, 0x76, 0x22, 0xd1, 0x06, 0xd7, 0xbb, 0x0e, 0xed, 0xab, 0x75, 0xee, 0xec, 0xac,
	0x7a, 0x3a, 0x52, 0x2f, 0x99, 0xb2, 0x44, 0xf5, 0x58, 0x14, 0x0f, 0x01, 0xc2, 0xdb, 0xdb, 0x64,
	0x7e, 0x89, 0x9b, 0xdd, 0xd1, 0xf9, 0x35, 0x63, 0xf9, 0xc9, 0x9f, 0x8c, 0x13, 0xcf, 0xaf, 0x99,
	0x25, 0xbf, 0x4d, 0x80, 0x75, 0xdc, 0xc1, 0x7e, 0x7e, 0x67, 0xd3, 0x1c, 0x73, 0x91, 0x20, 0xc5,
	0x34, 0xbf, 0x7e, 0xef, 0xd7, 0x23, 0xbd, 0xcf, 0xd2, 0xf4, 0xd5, 0x0f, 0x26, 0xcd, 0x7a, 0x86,
	0x34, 0x9b, 0x5f, 0xce, 0x40, 0x99, 0xf9, 0x8f, 0x8e, 0x3a, 0xff, 0x36, 0xdb, 0xcb, 0xa8, 0x33,
	0x45, 0x69, 0xd4, 0xb9, 0x9b, 0x21, 0xa3, 0x2e, 0xc6, 0x6e, 0x5f, 0xa3, 0x1e, 0x1b, 0xbf, 0x70,
	0xd4, 0x43, 0x9f, 0xfe, 0x24, 0x3e, 0x57, 0xe0, 0x6f, 0xa1, 0x6b, 0xf9, 0x1d, 0x6b, 0x9c, 0x00,
	0x46, 0x50, 0x89, 0x14, 0xc6, 0x69, 0x1e, 0xc6, 0x22, 0x5a, 0x90, 0xc3, 0x90, 0xdf, 0x13, 0x7d,
	0xdc, 0x11, 0x58, 0xb7, 0x27, 0xdc, 0x89, 0x61, 0x5c, 0x88, 0x3b, 0x02, 0xd8, 0x06, 0xb8, 0x93,
	0x38, 0xc3, 0xe1, 0xd7, 0x07, 0x29, 0x67, 0x18, 0xe2, 0xce, 0x60, 0x22, 0x42, 0xdc, 0x89, 0x5f,
	0x2f, 0x4d, 0x0e, 0x77, 0xa4, 0xaa, 0x45, 0x1b, 0x76, 0x80, 0x0e, 0x1f, 0x29, 0xb0, 0x94, 0x7c,
	0xd1, 0x9a, 0x5c, 0x2c, 0x0d, 0x1e, 0xcb, 0x8a, 0x7a, 0x26, 0xe5, 0x04, 0xe5, 0xdf, 0x11, 0x1c,
	0x1c, 0x5e, 0xef, 0xc4, 0xdd, 0xd7, 0xe8, 0x7a, 0x37, 0x63, 0xf5, 0x96, 0x61, 0xf4, 0x20, 0x70,
	0x70, 0xf7, 0x7a, 0x7f, 0xac, 0xc0, 0x52, 0xf2, 0x2d, 0x7f, 0x72, 0xb1, 0x5c, 0xe0, 0xb1, 0xd4,
	0x9b, 0xe7, 0xd2, 0x63, 0x89, 0x55, 0x7c, 0x80, 0xcc, 0xbc, 0xe2, 0x93, 0x42, 0x66, 0x09, 0xaa,
	0x42, 0x64, 0x3e, 0xa0, 0xc2, 0xd7, 0xb3, 0x16, 0x5e, 0x44, 0x71, 0xa0, 0x85, 0xaf, 0x67, 0x2e,
	0x7c, 0xf3, 0xfb, 0x02, 0xcc, 0x85, 0xb1, 0x04, 0x8c, 0x41, 0x60, 0xf6, 0x06, 0xa6, 0xd2, 0x37,
	0x47, 0x06, 0xde, 0xa8, 0xa5, 0x83, 0xa9, 0x84, 0xe4, 0xf2, 0xd4, 0xf1, 0x83, 0x79, 0x0c, 0x47,
	0x19, 0x34, 0xca, 0x10, 0x9e, 0x05, 0x42, 0xb3, 0x41, 0xf7, 0x3c, 0xf7, 0x5b, 0x41, 0x33, 0x11,
	0xbc, 0x76, 0xe0, 0x58, 0x1c, 0x6d, 0xd0, 0xbf, 0x32, 0x7e, 0xf8, 0x8d, 0x4c, 0x73, 0x81, 0xbb,
	0x9b, 0x53, 0x67, 0xe2, 0xed, 0xed, 0xc0, 0xb1, 0xf8, 0xbc, 0x25, 0x3d, 0xa6, 0x7c, 0x77, 0x67,
	0xf1, 0xd8, 0x4c, 0x78, 0xdc, 0x81, 0x63, 0xf1, 0x46, 0xdb, 0xe7, 0x58, 0xf9, 0x67, 0x58, 0x4f,
	0x9e, 0xe1, 0x55, 0x02, 0xc8, 0x76, 0xdb, 0xb1, 0x30, 0xaf, 0x96, 0xd8, 0xa4, 0x6d, 0x30, 0x23,
	0x1b, 0xca, 0x9b, 0x17, 0xdb, 0x84, 0x3e, 0xea, 0x6d, 0x35, 0x5a, 0x76, 0x57, 0xe3, 0x72, 0x57,
	0x0d, 0x0f, 0x6b, 0x6d, 0xfb, 0x3f, 0x6d, 0x6c, 0x71, 0x47, 0xda, 0x40, 0xdb, 0x70, 0x88, 0x18,
	0x99, 0xcb, 0xec, 0xcf, 0x4b, 0x45, 0xf9, 0x3c, 0x57, 0x5c, 0xbf, 0x79, 0xed, 0xde, 0x1b, 0x6b,
	0x1b, 0x37, 0xb7, 0x8e, 0x70, 0xe1, 0xff, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0xab, 0xe5, 0x01,
	0x89, 0x9a, 0x21, 0x00, 0x00,
}
