// Code generated by protoc-gen-go. DO NOT EDIT.
// source: analysis.proto

package analysis // import "github.com/dictyBase/go-genproto/dictybaseapis/analysis"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Various parameters required for creating a blast database
type BlastDbRequest struct {
	// sequence needed for database, provided in chunks
	SeqChunk []byte `protobuf:"bytes,1,opt,name=seq_chunk,json=seqChunk,proto3" json:"seq_chunk,omitempty"`
	// ncbi taxonid of the organism
	TaxonId string `protobuf:"bytes,2,opt,name=taxon_id,json=taxonId,proto3" json:"taxon_id,omitempty"`
	// name of the database
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// human readable description of the database
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Type of sequence, nucleotide or protein
	Seqtype              string   `protobuf:"bytes,5,opt,name=seqtype,proto3" json:"seqtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlastDbRequest) Reset()         { *m = BlastDbRequest{} }
func (m *BlastDbRequest) String() string { return proto.CompactTextString(m) }
func (*BlastDbRequest) ProtoMessage()    {}
func (*BlastDbRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_analysis_383897d4813d5b10, []int{0}
}
func (m *BlastDbRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlastDbRequest.Unmarshal(m, b)
}
func (m *BlastDbRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlastDbRequest.Marshal(b, m, deterministic)
}
func (dst *BlastDbRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlastDbRequest.Merge(dst, src)
}
func (m *BlastDbRequest) XXX_Size() int {
	return xxx_messageInfo_BlastDbRequest.Size(m)
}
func (m *BlastDbRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlastDbRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlastDbRequest proto.InternalMessageInfo

func (m *BlastDbRequest) GetSeqChunk() []byte {
	if m != nil {
		return m.SeqChunk
	}
	return nil
}

func (m *BlastDbRequest) GetTaxonId() string {
	if m != nil {
		return m.TaxonId
	}
	return ""
}

func (m *BlastDbRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlastDbRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlastDbRequest) GetSeqtype() string {
	if m != nil {
		return m.Seqtype
	}
	return ""
}

// Similar to the BlastDbParams except the sequence chunks
type BlastDbParams struct {
	// name of the sequence file
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// ncbi taxonid of the organism
	TaxonId string `protobuf:"bytes,2,opt,name=taxon_id,json=taxonId,proto3" json:"taxon_id,omitempty"`
	// name of the database
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// human readable description of the database
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Type of sequence, nucleotide or protein
	Seqtype              string   `protobuf:"bytes,5,opt,name=seqtype,proto3" json:"seqtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlastDbParams) Reset()         { *m = BlastDbParams{} }
func (m *BlastDbParams) String() string { return proto.CompactTextString(m) }
func (*BlastDbParams) ProtoMessage()    {}
func (*BlastDbParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_analysis_383897d4813d5b10, []int{1}
}
func (m *BlastDbParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlastDbParams.Unmarshal(m, b)
}
func (m *BlastDbParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlastDbParams.Marshal(b, m, deterministic)
}
func (dst *BlastDbParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlastDbParams.Merge(dst, src)
}
func (m *BlastDbParams) XXX_Size() int {
	return xxx_messageInfo_BlastDbParams.Size(m)
}
func (m *BlastDbParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BlastDbParams.DiscardUnknown(m)
}

var xxx_messageInfo_BlastDbParams proto.InternalMessageInfo

func (m *BlastDbParams) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *BlastDbParams) GetTaxonId() string {
	if m != nil {
		return m.TaxonId
	}
	return ""
}

func (m *BlastDbParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlastDbParams) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BlastDbParams) GetSeqtype() string {
	if m != nil {
		return m.Seqtype
	}
	return ""
}

func init() {
	proto.RegisterType((*BlastDbRequest)(nil), "dictybase.analysis.BlastDbRequest")
	proto.RegisterType((*BlastDbParams)(nil), "dictybase.analysis.BlastDbParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalysisServiceClient interface {
	// Create a blast database from the provided sequence
	CreateBlastDb(ctx context.Context, opts ...grpc.CallOption) (AnalysisService_CreateBlastDbClient, error)
}

type analysisServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnalysisServiceClient(cc *grpc.ClientConn) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) CreateBlastDb(ctx context.Context, opts ...grpc.CallOption) (AnalysisService_CreateBlastDbClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AnalysisService_serviceDesc.Streams[0], "/dictybase.analysis.AnalysisService/CreateBlastDb", opts...)
	if err != nil {
		return nil, err
	}
	x := &analysisServiceCreateBlastDbClient{stream}
	return x, nil
}

type AnalysisService_CreateBlastDbClient interface {
	Send(*BlastDbRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type analysisServiceCreateBlastDbClient struct {
	grpc.ClientStream
}

func (x *analysisServiceCreateBlastDbClient) Send(m *BlastDbRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *analysisServiceCreateBlastDbClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
type AnalysisServiceServer interface {
	// Create a blast database from the provided sequence
	CreateBlastDb(AnalysisService_CreateBlastDbServer) error
}

func RegisterAnalysisServiceServer(s *grpc.Server, srv AnalysisServiceServer) {
	s.RegisterService(&_AnalysisService_serviceDesc, srv)
}

func _AnalysisService_CreateBlastDb_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalysisServiceServer).CreateBlastDb(&analysisServiceCreateBlastDbServer{stream})
}

type AnalysisService_CreateBlastDbServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*BlastDbRequest, error)
	grpc.ServerStream
}

type analysisServiceCreateBlastDbServer struct {
	grpc.ServerStream
}

func (x *analysisServiceCreateBlastDbServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *analysisServiceCreateBlastDbServer) Recv() (*BlastDbRequest, error) {
	m := new(BlastDbRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AnalysisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dictybase.analysis.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateBlastDb",
			Handler:       _AnalysisService_CreateBlastDb_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "analysis.proto",
}

func init() { proto.RegisterFile("analysis.proto", fileDescriptor_analysis_383897d4813d5b10) }

var fileDescriptor_analysis_383897d4813d5b10 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0x64, 0x43, 0x3f, 0x92, 0x15, 0x29, 0xd2, 0x1e, 0x2a, 0xcb, 0xad, 0x44, 0xc8, 0x29, 0x97,
	0xee, 0x4a, 0x20, 0x71, 0xe1, 0x42, 0x9d, 0x72, 0xc8, 0x05, 0xa2, 0xc0, 0x01, 0xb8, 0x44, 0xcf,
	0xf1, 0xab, 0xbb, 0xaa, 0xbd, 0x6b, 0x7b, 0xd7, 0x2d, 0xfe, 0x3b, 0x5c, 0xe1, 0x3f, 0x21, 0xf1,
	0x2b, 0x38, 0xa2, 0x5d, 0xdb, 0x11, 0x16, 0xdc, 0x7b, 0x5b, 0xcf, 0xbc, 0x99, 0x37, 0xd6, 0x1b,
	0x7a, 0x02, 0x0a, 0xb2, 0xc6, 0x48, 0xc3, 0x8b, 0x4a, 0x5b, 0xcd, 0x58, 0x22, 0x77, 0xb6, 0x89,
	0xc1, 0x20, 0xef, 0x99, 0xf0, 0x2c, 0xd5, 0x3a, 0xcd, 0x50, 0xf8, 0x89, 0xb8, 0xbe, 0x16, 0x98,
	0x17, 0xb6, 0x69, 0x05, 0xe1, 0x79, 0x47, 0x42, 0x21, 0x05, 0x28, 0xa5, 0x2d, 0x58, 0xa9, 0x55,
	0x67, 0x17, 0xbe, 0x4a, 0xa5, 0xbd, 0xa9, 0x63, 0xbe, 0xd3, 0xb9, 0xc8, 0xef, 0xa5, 0xbd, 0xd5,
	0xf7, 0x22, 0xd5, 0x17, 0x9e, 0xbc, 0xb8, 0x83, 0x4c, 0x26, 0x60, 0x75, 0x65, 0xc4, 0xfe, 0xd9,
	0xea, 0xe6, 0x3f, 0x08, 0x3d, 0x89, 0x32, 0x30, 0xf6, 0x2a, 0xde, 0x60, 0x59, 0xa3, 0xb1, 0xec,
	0x8c, 0x4e, 0x0c, 0x96, 0xdb, 0xdd, 0x4d, 0xad, 0x6e, 0x03, 0x32, 0x23, 0x8b, 0x27, 0x9b, 0xb1,
	0xc1, 0x72, 0xe9, 0xbe, 0xd9, 0x73, 0x3a, 0xb6, 0xf0, 0x55, 0xab, 0xad, 0x4c, 0x82, 0xd1, 0x8c,
	0x2c, 0x26, 0xd1, 0xd1, 0xaf, 0x9f, 0xcf, 0x46, 0x9f, 0xc8, 0xe6, 0xd8, 0xe3, 0xab, 0x84, 0x85,
	0xf4, 0x40, 0x41, 0x8e, 0xc1, 0xe3, 0x01, 0xed, 0x31, 0x76, 0x4e, 0x0f, 0xad, 0xb4, 0x19, 0x06,
	0x07, 0x03, 0xb2, 0x05, 0xd9, 0x8c, 0x1e, 0x1b, 0x2c, 0x6d, 0x53, 0x60, 0x70, 0x38, 0xf4, 0xee,
	0xe0, 0xf9, 0x77, 0x42, 0xa7, 0x5d, 0xdc, 0x35, 0x54, 0x90, 0x1b, 0x97, 0xf6, 0x5a, 0x66, 0xb8,
	0xf5, 0x2b, 0x5d, 0xda, 0xc9, 0x66, 0xec, 0x80, 0x77, 0x6e, 0xdd, 0xc3, 0xa6, 0x7d, 0x11, 0xd3,
	0xa7, 0x97, 0xdd, 0x6d, 0x3f, 0x60, 0x75, 0x27, 0x77, 0xc8, 0xde, 0xd3, 0xe9, 0xb2, 0x42, 0xb0,
	0xd8, 0xfd, 0x05, 0x9b, 0xf3, 0x7f, 0x8b, 0xc0, 0x87, 0x17, 0x09, 0x4f, 0x79, 0x7b, 0x7b, 0xde,
	0x17, 0x83, 0xbf, 0x75, 0xc5, 0x98, 0x3f, 0x5a, 0x90, 0xa8, 0xa1, 0xa7, 0xba, 0x4a, 0xff, 0x63,
	0x12, 0x4d, 0xfb, 0xdd, 0x6b, 0xa7, 0x5a, 0x93, 0x2f, 0x6f, 0xfe, 0xea, 0x88, 0x9f, 0x8f, 0xc0,
	0xa0, 0x6b, 0x49, 0x8a, 0xca, 0x3b, 0x8b, 0xbd, 0x0b, 0x14, 0xd2, 0x88, 0xde, 0xe9, 0x75, 0xff,
	0xf8, 0x4d, 0xc8, 0xb7, 0xd1, 0xf8, 0x6a, 0xb5, 0xfc, 0xf8, 0xf9, 0x72, 0xbd, 0x8a, 0x8f, 0xbc,
	0xe8, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x23, 0x29, 0x41, 0xdb, 0x02, 0x00, 0x00,
}
