// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dictybase/feature_annotation/feature_annotation_organism.proto

package feature_annotation

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "github.com/dictyBase/go-genproto/dictybaseapis/organism"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *OrganismFeatureLink) Validate() error {
	if !(this.OrganismId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("OrganismId", fmt.Errorf(`value '%v' must be greater than '0'`, this.OrganismId))
	}
	if this.FeatureId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("FeatureId", fmt.Errorf(`value '%v' must not be an empty string`, this.FeatureId))
	}
	return nil
}
func (this *OrganismFeatureUpdate) Validate() error {
	if this.FeatureId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("FeatureId", fmt.Errorf(`value '%v' must not be an empty string`, this.FeatureId))
	}
	if !(this.NewOrganismId > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("NewOrganismId", fmt.Errorf(`value '%v' must be greater than '0'`, this.NewOrganismId))
	}
	return nil
}
