// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dictybase/feature_annotation/feature_annotation_organism.proto

package feature_annotation

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/dictyBase/go-genproto/dictybaseapis/organism"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *OrganismFeatureLink) Validate() error {
	return nil
}
func (this *OrganismFeatureUpdate) Validate() error {
	return nil
}
