// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

/*
Package jsonapi is a generated protocol buffer package.

It is generated from these files:
	payload.proto
	request.proto

It has these top-level messages:
	Data
	Links
	PaginationLinks
	Pagination
	Meta
	GetRequest
	ListRequest
	DeleteRequest
*/
package jsonapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A [resource identifier object](http://jsonapi.org/format/#document-resource-identifier-objects).
type Data struct {
	// The resource name.
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Unique id.
	Id int64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// A container for http links.
type Links struct {
	// A http link. It points to the resource itself.
	Self string `protobuf:"bytes,1,opt,name=self" json:"self,omitempty"`
	// A http link. It points to a related resource.
	Related string `protobuf:"bytes,2,opt,name=related" json:"related,omitempty"`
}

func (m *Links) Reset()                    { *m = Links{} }
func (m *Links) String() string            { return proto.CompactTextString(m) }
func (*Links) ProtoMessage()               {}
func (*Links) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Links) GetSelf() string {
	if m != nil {
		return m.Self
	}
	return ""
}

func (m *Links) GetRelated() string {
	if m != nil {
		return m.Related
	}
	return ""
}

// A container for pagination links.
type PaginationLinks struct {
	// A http link to the resource itself.
	Self string `protobuf:"bytes,1,opt,name=self" json:"self,omitempty"`
	// A http link to the next page of data.
	Next string `protobuf:"bytes,2,opt,name=next" json:"next,omitempty"`
	// A http link to the previous page of data.
	Prev string `protobuf:"bytes,3,opt,name=prev" json:"prev,omitempty"`
	// A http link to the last page of data.
	Last string `protobuf:"bytes,4,opt,name=last" json:"last,omitempty"`
	// A http link to the first page of data.
	First string `protobuf:"bytes,5,opt,name=first" json:"first,omitempty"`
}

func (m *PaginationLinks) Reset()                    { *m = PaginationLinks{} }
func (m *PaginationLinks) String() string            { return proto.CompactTextString(m) }
func (*PaginationLinks) ProtoMessage()               {}
func (*PaginationLinks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PaginationLinks) GetSelf() string {
	if m != nil {
		return m.Self
	}
	return ""
}

func (m *PaginationLinks) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *PaginationLinks) GetPrev() string {
	if m != nil {
		return m.Prev
	}
	return ""
}

func (m *PaginationLinks) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *PaginationLinks) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

// A container for various pagination properties
type Pagination struct {
	// Total number of entries, regardless of pages.
	Records int64 `protobuf:"varint,1,opt,name=records" json:"records,omitempty"`
	// Total number of pages.
	Total int64 `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	// Number of entries per page.
	Size int64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// Current page number.
	Number int64 `protobuf:"varint,4,opt,name=number" json:"number,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Pagination) GetRecords() int64 {
	if m != nil {
		return m.Records
	}
	return 0
}

func (m *Pagination) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

// Top level meta container.
type Meta struct {
	Pagination *Pagination `protobuf:"bytes,1,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Meta) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "dictybase.api.jsonapi.Data")
	proto.RegisterType((*Links)(nil), "dictybase.api.jsonapi.Links")
	proto.RegisterType((*PaginationLinks)(nil), "dictybase.api.jsonapi.PaginationLinks")
	proto.RegisterType((*Pagination)(nil), "dictybase.api.jsonapi.Pagination")
	proto.RegisterType((*Meta)(nil), "dictybase.api.jsonapi.Meta")
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x24, 0x1f, 0xad, 0xf6, 0xf9, 0x05, 0x8b, 0x4a, 0xbc, 0xd5, 0x9c, 0x8a, 0x60, 0x02, 0x8a,
	0x27, 0x4f, 0x8d, 0xbd, 0x14, 0x14, 0x42, 0xf0, 0xa2, 0xb7, 0x97, 0x66, 0x9b, 0xae, 0xa6, 0xd9,
	0x25, 0xbb, 0x55, 0x2b, 0xf8, 0x67, 0xfc, 0x95, 0x1e, 0x65, 0x77, 0xd3, 0xd6, 0x43, 0x3d, 0x65,
	0x66, 0x78, 0xf3, 0xe6, 0x65, 0x07, 0x0e, 0x04, 0x2e, 0x2b, 0x8e, 0x45, 0x24, 0x1a, 0xae, 0x38,
	0x39, 0x29, 0xd8, 0x44, 0x2d, 0x73, 0x94, 0x34, 0x42, 0xc1, 0xa2, 0x17, 0xc9, 0x6b, 0x14, 0x2c,
	0xbc, 0x00, 0x7f, 0x84, 0x0a, 0x09, 0x01, 0x5f, 0x2d, 0x05, 0x0d, 0x9c, 0xbe, 0x33, 0xe8, 0x65,
	0x06, 0x93, 0x43, 0x70, 0x59, 0x11, 0xb8, 0x7d, 0x67, 0xe0, 0x65, 0x2e, 0x2b, 0xc2, 0x1b, 0xe8,
	0xdc, 0xb3, 0xfa, 0x55, 0xea, 0x61, 0x49, 0xab, 0xe9, 0x6a, 0x58, 0x63, 0x12, 0xc0, 0x4e, 0x43,
	0x2b, 0x54, 0xd4, 0x3a, 0x7a, 0xd9, 0x8a, 0x86, 0xef, 0x70, 0x94, 0x62, 0xc9, 0x6a, 0x54, 0x8c,
	0xd7, 0xff, 0x2f, 0x20, 0xe0, 0xd7, 0xf4, 0x43, 0xb5, 0x6e, 0x83, 0xb5, 0x26, 0x1a, 0xfa, 0x16,
	0x78, 0x56, 0xd3, 0x58, 0x6b, 0x15, 0x4a, 0x15, 0xf8, 0x56, 0xd3, 0x98, 0x1c, 0x43, 0x67, 0xca,
	0x1a, 0xa9, 0x82, 0x8e, 0x11, 0x2d, 0x09, 0x67, 0x00, 0x9b, 0x60, 0x7b, 0xe0, 0x84, 0x37, 0x85,
	0x34, 0xb1, 0x5e, 0xb6, 0xa2, 0xda, 0xad, 0xb8, 0xc2, 0xaa, 0xfd, 0x55, 0x4b, 0xcc, 0x8d, 0xec,
	0x93, 0x9a, 0x6c, 0x2f, 0x33, 0x98, 0x9c, 0x42, 0xb7, 0x5e, 0xcc, 0x73, 0xda, 0x98, 0x74, 0x2f,
	0x6b, 0x59, 0x38, 0x06, 0xff, 0x81, 0x2a, 0x24, 0x43, 0x00, 0xb1, 0x4e, 0x34, 0x31, 0x7b, 0x57,
	0xe7, 0xd1, 0xd6, 0x97, 0x8f, 0x36, 0xa7, 0x65, 0x7f, 0x4c, 0xc9, 0x17, 0x9c, 0xf1, 0xa6, 0xdc,
	0xee, 0x49, 0xf6, 0x53, 0xdb, 0x69, 0xaa, 0x2b, 0x4d, 0x9d, 0xe7, 0xa4, 0x64, 0x6a, 0xb6, 0xc8,
	0xa3, 0x09, 0x9f, 0xc7, 0xc6, 0x91, 0xa0, 0xa4, 0x71, 0xc9, 0x2f, 0x4b, 0x5a, 0x9b, 0xda, 0xe3,
	0xf5, 0x1e, 0x14, 0x4c, 0xc6, 0x28, 0x58, 0xdc, 0xee, 0xba, 0x6d, 0xbf, 0x3f, 0x8e, 0xf3, 0xed,
	0xee, 0x8e, 0xc6, 0x77, 0x8f, 0x4f, 0xc3, 0x74, 0x9c, 0x77, 0x8d, 0xed, 0xfa, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x55, 0x64, 0x82, 0xa0, 0x3e, 0x02, 0x00, 0x00,
}
