// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: request.proto

package jsonapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetRequest) Validate() error {
	return nil
}
func (this *RelationshipRequest) Validate() error {
	return nil
}
func (this *RelationshipRequestWithPagination) Validate() error {
	return nil
}
func (this *ListRequest) Validate() error {
	return nil
}
func (this *SimpleListRequest) Validate() error {
	return nil
}
func (this *DeleteRequest) Validate() error {
	return nil
}
